### ISSUE TITLE
Proposal document type: "XXXX" shown in cover page

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rsd#10]
In a proposal type document, a "XXXX" is shown on the cover page (see image).

![screen shot 2018-07-09 at 12 41 06 pm](https://user-images.githubusercontent.com/11865/42431053-94524186-8375-11e8-952f-463689009c6f.png)

**Comment by opoudjis** [comment]
That's a placeholder for the (technical) committee, which happens to be missing in the source document.

Should I issue a warning if the technical committee is missing from the document, and keep outputting something like this, or should I silently suppress output of the committee placeholder? This issue extends to all gems, since they assume that committees are mandatory.

**Comment by ronaldtse** [comment]
Maybe it should be empty instead of "XXXX" if there's no entry.

However, in the README, it says the committee is `:committee:`.

But I can't get it to show, and also `:technical-committee:` doesn't work?

**Comment by opoudjis** [comment]
... Fixed: now correctly picking up `:committee:`, and  not populating it with XXXX as default.
