### ISSUE TITLE
Differentiated ISO refs and "other" refs in Norm Refs section

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rsd#8]
Notice that the ISO refs are not indented but the other refs are. They should all be indented since it's a list.

![screen shot 2018-07-09 at 7 19 37 am](https://user-images.githubusercontent.com/11865/42425063-a71a08b6-8349-11e8-9947-8c922176484e.png)

**Comment by opoudjis** [comment]
I am not getting that behaviour in my instance, because i've updated the stylesheet to render NormRef and Biblio identically. I am noticing that non-ISO references under Normative references are being styled as Biblio; that's wrong, and I'm fixing it in isodoc. 

Please confirm you're running gem version 0.3.2.

**Comment by opoudjis** [comment]
Fixed isodoc: I was styling non-ISO references under Norm Ref as "Biblio", but whatever the motivation for that was, it's obsolete. 

(I remember what the motivation was: to have hanging indent numbers for non-ISO references, like they appear in Biblio. But that turned out to be wrong: non-ISO references under NormRef in ISO standards are rendered the same way as ISO references, by presupposing that they are standards and have a distinctive prefix.)
